apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.10.1 # Official Kibana image
          ports:
            - containerPort: 5601  # Default Kibana port
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200  # Points to the Elasticsearch service

---

apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
  type: ClusterIP  # Accessible only within the cluster (can be changed to NodePort for external access)